### ISSUE TITLE
Hello SiChiTong

### ISSUE THREAD

**Issue by taoso** [SiChiTong/ROS_Car#1]

**Comment by epii1** [comment]
Hi @SiChiTong ,

实在冒昧，又来给你留言。因为我看你在 GitHub 上比较活跃，期待能看到我的留言。

我自已的博客域名是 https://taoshu.in 。所以想着能不能注册 github.com/taoshu 这个 ID。然而很可惜，这个 ID 已经被注册。我是想联系这个 ID 的所有者，但他没有留下联系信息。

但是，我注意到 github.com/taoshu 的关注者只有你。于是我猜测可能是由你注册的，或者可能你认识这个 ID 的注册人。所以才来冒昧打扰。

期待能得到你的回复或者帮助。感激不尽🙏

**Comment by epii1** [comment]
@SiChiTong 兄，求翻牌 😭
